# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       upower
Summary:    Power Management Service
Version:    0.9.15
Release:    2
Group:      System/Libraries
License:    GPLv2+
URL:        http://upower.freedesktop.org/
Source0:    http://upower.freedesktop.org/releases/upower-%{version}.tar.xz
Source100:  upower.yaml
Requires:   polkit >= 0.92
Requires:   udev
Requires:   pm-utils >= 1.2.2.1
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(gudev-1.0)
BuildRequires:  pkgconfig(libusb-1.0)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(polkit-gobject-1)
BuildRequires:  libtool
BuildRequires:  intltool
BuildRequires:  gettext
Provides:   DeviceKit-power
Obsoletes:   DeviceKit-power < 1:0.9.0-2


%description
UPower (formerly DeviceKit-power) provides a daemon, API and command
line tools for managing power devices attached to the system.



%package devel
Summary:    Headers and libraries for UPower
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   DeviceKit-power-devel
Obsoletes:   DeviceKit-power-devel < 1:0.9.0-2

%description devel
Headers and libraries for UPower.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-gtk-doc

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post
%find_lang upower



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files -f upower.lang
%defattr(-,root,root,-)
# >> files
%doc NEWS COPYING AUTHORS HACKING README
%{_libdir}/libupower-glib.so.*
%{_sysconfdir}/dbus-1/system.d/*.conf
/lib/udev/rules.d/*.rules
%dir %{_localstatedir}/lib/upower
%dir %{_sysconfdir}/UPower
%config %{_sysconfdir}/UPower/UPower.conf
%{_bindir}/*
%{_libexecdir}/*
%{_datadir}/polkit-1/actions/*.policy
%{_datadir}/dbus-1/system-services/*.service
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/dbus-1/interfaces/*.xml
%{_libdir}/libupower-glib.so
%{_libdir}/pkgconfig/*.pc
%dir %{_includedir}/libupower-glib
%{_includedir}/libupower-glib/up-*.h
%{_includedir}/libupower-glib/upower.h
# << files devel

